# Generated by Django 3.1.7 on 2021-04-06 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tradeaccount',
            table='TradeAccount',
        ),
    ]
