# Generated by Django 3.1.7 on 2021-04-06 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210405_2009'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tradeaccount',
            table=None,
        ),
    ]
