# Generated by Django 3.1.7 on 2021-04-06 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210405_2018'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TradeAccount',
        ),
    ]
