# Generated by Django 3.1.7 on 2021-04-11 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210406_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTradeAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('trade_account_id', models.IntegerField()),
                ('role', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'UserTradeAccount',
            },
        ),
    ]
