# Generated by Django 3.1.7 on 2021-04-06 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20210327_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='trade_account',
            field=models.IntegerField(default=1),
        ),
    ]
