# Generated by Django 3.1.7 on 2021-04-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_user_trade_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='trade_account',
            field=models.IntegerField(null=True),
        ),
    ]
