# Generated by Django 3.1.7 on 2021-04-06 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_auto_20210406_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='trade_account',
            field=models.CharField(max_length=20),
        ),
    ]
