# Generated by Django 3.1.7 on 2021-04-09 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_auto_20210406_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='trade_account',
            field=models.CharField(default='[]', max_length=20),
        ),
    ]
