# Generated by Django 3.1.7 on 2021-04-10 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_auto_20210410_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='trade_account',
            field=models.CharField(default='[]', max_length=255),
        ),
    ]
