# Generated by Django 3.1.7 on 2021-04-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_auto_20210410_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='trade_account',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
