# Generated by Django 3.1.7 on 2021-04-11 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_remove_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='trade_account',
        ),
    ]
